name: Build and Release mosac for MacOS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    if: contains(github.event.head_commit.message, '[RELEASE]')
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure Go env from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Dependencies
        run: |
          go mod download
          go mod verify

      - name: Version (from commit message)
        id: extract_version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          EXTRACTED_VERSION=$(printf "%s" "$COMMIT_MSG" \vert{} grep -ioP 'v\d+(\.\d+)*' \vert{}\vert{} echo "v0.0.0-${GITHUB_SHA::7}")
          echo "VERSION=$EXTRACTED_VERSION" >> $GITHUB_ENV

      - name: MacOS compilation
        env:
          CGO_ENABLED: 0
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -ldflags="-s -w" -o mosac cmd/mosac/main.go

      - name: Ad-Hoc Codesign for Apple Silicon
        run: |
          codesign --force --options runtime --deep --sign - ./mosac

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            MacOS (arm64) native binary.
            **Commit trigger:** `${{ github.event.head_commit.message }}`
          files: |
            mosac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}