name: Build and Release mosac for MacOS

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release for MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure Go env from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Dependencies
        run: |
          go mod download
          go mod verify

      - name: Build MacOS Binaries
        env:
          CGO_ENABLED: 0
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -ldflags="-s -w" -o mosac-arm64 cmd/mosac/main.go

      - name: Ad-Hoc Codesign
        run: |
          codesign --force --options runtime --deep --sign - ./mosac-arm64

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            mosac-arm64